### PR TITLE
Fix issue-5

### LINKED ISSUE #5: Allow Decimal Values for Product Dimensions
## **Issue Description:**
Currently, the application only accepts integer values for product dimensions (width, depth, height). However, in real-world scenarios, product dimensions can often be in decimal points (e.g., 12.5cm). This limitation can impact the accuracy of the palletization calculation.

## **Proposed Solution:**
Modify the application to accept decimal values for product dimensions. Update the input validation logic and ensure that the calculations can handle decimal points for width, depth, and height. Additionally, adjust the UI to provide a better user experience when entering decimal values.

## **Steps to Reproduce:**
1. Open the application.
2. Enter a product with decimal values for width, depth, or height (e.g., 12.5cm).
3. Attempt to calculate pallet size. and ensure everything works

## **Expected Behavior:**
The application should accept and correctly process decimal values for product dimensions without any errors. Ensure that the palletization algorithm handles decimal points appropriately.

## **Additional Information:**
- Update relevant input validation functions.
- Adjust the user interface to handle decimal input for product dimensions.
- Test the application with various product dimensions, including both integer and decimal values.

**Note:**
Make sure to update the code and user interface to handle decimal values appropriately, ensuring accurate palletization calculations.

### PR DESCRIPTION
**Pull request by yaki3355**
## Motivation
Allow Decimal Values for Product Dimensions

Closes #5 

## Implemention
Add step feature to input fields in index.html
Use parseFloat instead of parseInt in script.js

## Testing
manual testing

## Checklist
I have checked the workaround.
I have tested this change thoroughly.

### CODE REVIEW

**Comment by dhextras** [comment]
@yaki3355 First of all **REALLY** appreciated your _contribution_ but, 

- Remove the steps part in html which is not necessary.
- Update the `generatePalletDisplay` function in line 403. To make sure to round up Width, Depth & Hight. Use `Math.round()` Reference line 432.
- Make sure the styling is aligned perfectly. I think you already checked it but just in case.
- Btw get th latest version and do the changes.

### Really looking forward to ur correction. And future contribution

**Comment by yaki3355** [comment]
> @yaki3355 First of all **REALLY** appreciated your _contribution_ but,
> 
> * Remove the steps part in html which is not necessary.
> * Update the `generatePalletDisplay` function in line 403. To make sure to round up Width, Depth & Hight. Use `Math.round()` Reference line 432.
> * Make sure the styling is aligned perfectly. I think you already checked it but just in case.
> * Btw get th latest version and do the changes.
> 
> ### Really looking forward to ur correction. And future contribution

Hey @dhextras 
Do the same calculation like in line 432? Including adding 10?

**Comment by dhextras** [comment]
> > @yaki3355 First of all **REALLY** appreciated your _contribution_ but,
> > 
> > * Remove the steps part in html which is not necessary.
> > * Update the `generatePalletDisplay` function in line 403. To make sure to round up Width, Depth & Hight. Use `Math.round()` Reference line 432.
> > * Make sure the styling is aligned perfectly. I think you already checked it but just in case.
> > * Btw get th latest version and do the changes.
> > 
> > ### Really looking forward to ur correction. And future contribution
> 
> Hey @dhextras 
> Do the same calculation like in line 432? Including adding 10?

@yaki3355  No just simply use it. Also use Math.ceil(l instead of Math.round() on each width, Depth & height.nothing additional. 


Heres an example:

```js
const palletWidth = Math.ceil(pallet.palletWidth); // Line 419
.....
const ratioText = `Pallet Ratio (W x D x H): ${palletWidth} X ......
... cm`; // Line 421
```
Just update all three of em like this.

Note: Make sure to get the updated source code before making the changes

**Comment by dhextras** [comment]
@yaki3355 🥳 looks good thanks for your contributions looking forward for further contribution from you.

Btw are u from brad dc.

**Comment by yaki3355** [comment]
> @yaki3355 🥳 looks good thanks for your contributions looking forward for further contribution from you.
> 
> Btw are u from brad dc.

Nope. What is it?

**Comment by dhextras** [comment]
> > @yaki3355 🥳 looks good thanks for your contributions looking forward for further contribution from you.
> > 
> > Btw are u from brad dc.
> 
> Nope. What is it?

Well its a discord server for programmers.
Where u can find collaborators and contributors for your project as well as u can contribute to the project you like. Getting your project reviewed and stuff. Really recommand it.

Heres the link if ud like to join https://discord.com/invite/cloudzy

**Pull request merged**
